# k8s/mysql/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: musicplace
data:
  primary.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    gtid_mode=ON
    enforce-gtid-consistency=ON
    log-slave-updates=ON
  replica.cnf: |
    [mysqld]
    gtid_mode=ON
    enforce-gtid-consistency=ON
    log-slave-updates=ON
    read_only=ON
    super_read_only=ON
  entrypoint.sh: |
    FORCE_INITIAL_PRIMARY=$(cat /mnt/scripts/force-initial-primary 2>/dev/null || echo false)
    if [[ -d /var/lib/mysql/mysql ]]; then
    exec docker-entrypoint.sh mysqld
    fi
    if [[ "$FORCE_INITIAL_PRIMARY" == "true" ]]; then
    exec docker-entrypoint.sh mysqld
    fi

    wait $pid
