# k8s/mysql/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: musicplace
type: Opaque
stringData:
  root-password: "${MYSQL_ROOT_PASSWORD}"
  repl-password: "${MYSQL_REPL_PASSWORD}"
