apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-db-sa
  namespace: musicplace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-db-role
  namespace: musicplace
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "events", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["list", "get"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines", "chaosexperiments", "chaosresults"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-db-rolebinding
  namespace: musicplace
subjects:
  - kind: ServiceAccount
    name: litmus-db-sa
    namespace: musicplace
roleRef:
  kind: Role
  name: litmus-db-role
  apiGroup: rbac.authorization.k8s.io
